network:
  version: 2
  ethernets:
    <eth0>: # Replace with ethernet device name
      dhcp4: yes
      dhcp6: no
  wifis:
    <wlan0>: # Replace with wifi device name
      dhcp4: yes
      dhcp6: no
      access-points:
        "<network_ssid_name>":  # Replace with ssid
          password: "<**********>" # Replace with password
